INSERT INTO ROLE (ID, NAME) VALUES (1, 'ROLE_SUPER_ADMIN');
INSERT INTO ROLE (ID, NAME) VALUES (2, 'ROLE_ADMIN');
INSERT INTO ROLE (ID, NAME) VALUES (3, 'ROLE_MANAGER');
INSERT INTO ROLE (ID, NAME) VALUES (4, 'ROLE_USER');



--INSERT INTO USER (ID, NAME, USERNAME, PASSWORD, ROLE_ID) VALUES (1, 'john', 'john', 'john', 1);
--INSERT INTO USER (ID, NAME, USERNAME, PASSWORD, ROLE_ID) VALUES (2, 'john', 'john', 'john', 2);

--INSERT INTO USER (ID, NAME, USERNAME, PASSWORD, ROLE_ID) VALUES (3, 'george', 'george', 'george', 3);
--INSERT INTO USER (ID, NAME, USERNAME, PASSWORD, ROLE_ID) VALUES (4, 'george', 'george', 'george', 4);
